spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workboard
    username: workboard
    password: workboard123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080